@dropall
@drop

spool RebuildStage.log

purge recyclebin;

@@Stage/StageFunctions

@@Stage/S_ACCOM_TYPE_CORRECTIONS
@@Stage/S_BASIS_CORRECTIONS
@@Stage/S_CODES
@@Stage/S_CODE_TEXT_ITEMS
@@Stage/S_CODE_TYPES
@@Stage/S_COMPONENTS
@@Stage/S_DIMENSION_TYPES
@@Stage/S_DIMENSION_VALUES
@@Stage/S_DISPLACEMENT_STATUSES
@@Stage/S_DST_CODE_CORRECTIONS
@@Stage/S_LANGUAGES
@@Stage/S_LOCATION_ATTRIBUTE_TYPES
@@Stage/S_LOCATION_COUNTRIES
@@Stage/S_LOCATION_COUNTRY_NAMES
@@Stage/S_LOCATION_IDS
@@Stage/S_LOCATION_NAME_CORRECTIONS
@@Stage/S_LOCATION_REGIONS
@@Stage/S_LOCATION_REGION_NAMES
@@Stage/S_LOCATION_RELATIONSHIPS
@@Stage/S_LOCATION_RELATIONSHIP_TYPES
@@Stage/S_LOCATION_SUBDIVISIONS
@@Stage/S_LOCATION_TYPES
@@Stage/S_LOCATION_TYPE_VARIANTS
@@Stage/S_LOC_SEQ
@@Stage/S_MESSAGES
@@Stage/S_PERMISSIONS
@@Stage/S_POPULATION_TYPE_CORRECTIONS
@@Stage/S_ROLES
@@Stage/S_ROLE_COUNTRIES
@@Stage/S_SOURCE_CORRECTIONS
@@Stage/S_STATISTIC_TYPES
@@Stage/S_STATISTIC_TYPES_IN_GROUPS
@@Stage/S_STATISTIC_TYPE_GROUPS
@@Stage/S_STC_GROUP_ATTRIBUTE_TYPES
@@Stage/S_TEXT_TYPES
@@Stage/S_TEXT_TYPE_PROPERTIES

@@Stage/S_PPGS
@@Stage/S_PPG_CORRECTIONS

@@Stage/S_ASR_REFUGEES
@@Stage/S_ASR_DEMOGRAPHICS
@@Stage/S_ASR_RSD
@@Stage/S_ASR_IDPS
@@Stage/S_ASR_RETURNS
@@Stage/S_ASR_STATELESS
@@Stage/S_ASR_OOC

@@Stage/RefreshStageMViews

@@Stage/CheckStageIntegrity

spool off
